### ISSUE TITLE
Developer

### ISSUE THREAD

**Issue by webdv1pr** [veliovgroup/jobs#11]
This is test job post by test account. Don't mind it ;)

We are looking for experiences NEAR blockchain developer to join rapidly growing project.
All remote with weekly calls. Tasks and management done over GitHub.

Competitive salary 👨‍💻

__List__:

- one
- Two
- THREEE

Test, test, test... 🎙

**Comment by dr-dimitru** [comment]
Hello!
I'm interested in this position, please take a look at [my profile](https://jobs.openweb.dev/profile/1) and my GitHub account @dr-dimitru
