### ISSUE TITLE
Developer

### ISSUE THREAD

**Issue by doriancrutcher** [veliovgroup/jobs#12]
Create new and creative was for users to be able to take their Minecraft creations and mint them as NFTs for users to create, buy, sell, and trade!

**Comment by dr-dimitru** [comment]
Hello @doriancrutcher ,

We had to move things around, all profiles and jobs repos are moved under NEAR namespace and there was no clear way to move issues. I'm sorry for the inconvenience, but you would need to create a new account and repost a job post via [jobs.openweb.dev](https://jobs.openweb.dev/)
