### ISSUE TITLE
Hiring DAOveloper(s)

### ISSUE THREAD

**Issue by jlwaugh** [veliovgroup/jobs#13]
We are looking for someone to build a guild-specific frontend using the [v2 Sputnik DAO contract](https://github.com/near-daos/sputnik-dao-contract/tree/main/sputnikdao2). This would enable users to associate NEAR identities with "profiles" on [Ceramic Network](https://ceramic.network), the dataweb for open information.

[START HERE](https://github.com/metaguild/sputnik)

This particular [template](https://github.com/TrevorJTClarke/near-vue-tailwind) is built using a [Vue plugin](https://github.com/TrevorJTClarke/vue-near) for the [NEAR JavaScript API](https://near.github.io/near-api-js).

Recipe book for `near-api-js`: https://docs.near.org/docs/tutorials/front-end/naj-examples

VueJS not required ~ if you prefer other JavaScript libraries / frameworks, don't hesitate to apply!

**Comment by dr-dimitru** [comment]
Hello @jlwaugh ,

We had to move things around, all profiles and jobs repos are moved under NEAR namespace and there was no clear way to move issues. I'm sorry for the inconvenience, but you would need to create a new account and repost a job post via [jobs.openweb.dev](https://jobs.openweb.dev/)
