### ISSUE TITLE
Rust Developer

### ISSUE THREAD

**Issue by ImTheCodeFarmer** [veliovgroup/jobs#14]
We are looking for a Rust developer to help create a couple functions. 

- transferring tokens to one wallet from another
- minting a NFT on NEAR

**Comment by dr-dimitru** [comment]
Hello @jhammond2012 ,

We had to move things around, all profiles and jobs repos are moved under NEAR namespace and there was no clear way to move issues. I'm sorry for the inconvenience, but you would need to create a new account and repost a job post via [jobs.openweb.dev](https://jobs.openweb.dev/)
