### ISSUE TITLE
Web designer

### ISSUE THREAD

**Issue by webdv1pr** [veliovgroup/jobs#15]
We are looking for web designer and UX-pro

*This is test job, ignore it*

**Comment by dr-dimitru** [comment]
Hello @doriancrutcher ,

We had to move things around, all profiles and jobs repos are moved under NEAR namespace and there was no clear way to move issues. I'm sorry for the inconvenience, but you would need to create a new account and repost a job post via [jobs.openweb.dev](https://jobs.openweb.dev/)
