### ISSUE TITLE
Blockchain Developer

### ISSUE THREAD

**Issue by webdv1pr** [veliovgroup/jobs#5]
We are looking for highly skilled blockchain developer. v2

**Comment by dr-dimitru** [comment]
Hello!
I'm interested in this position please reach me over Gitter @dr-dimitru

**Comment by dr-dimitru** [comment]
Hello!
I'm interested in this position, please take a look at [my profile](http://127.0.0.1:5555/profile/1) and my GitHub account @dr-dimitru
